"""Narrow ports used by scenario orchestration."""

from __future__ import annotations

from typing import Protocol

from ..execution import CommandResult
from .models import ScenarioInstancePlan, ScenarioPlan, ScenarioResult, ScenarioTarget


class ContainerRuntime(Protocol):
    def require(self) -> None: ...

    def restart(self, plan: ScenarioPlan) -> None: ...

    def check(self, plan: ScenarioPlan) -> None: ...

    @staticmethod
    def target(instance: ScenarioInstancePlan) -> str: ...


class ComposeRuntime(Protocol):
    def require(self) -> None: ...

    def preflight(self, plan: ScenarioPlan) -> None: ...

    def prepare(self, plan: ScenarioPlan) -> ScenarioPlan: ...

    def remove(self, plan: ScenarioTarget) -> None: ...


class SessionRuntime(Protocol):
    def require(self) -> None: ...

    def session_exists(self, session: str) -> bool: ...

    def window_exists(self, session: str, window_name: str) -> bool: ...

    def panes(self, window: str) -> tuple[tuple[str, int], ...]: ...

    def create_window(self, session: str, window_name: str) -> bool: ...

    def configure_session(self, session: str, *, mouse: bool) -> None: ...

    def configure_window(self, window: str) -> None: ...

    def split_window(self, window: str, window_name: str) -> None: ...

    def tile(self, window: str, window_name: str) -> None: ...

    def start_pane(self, target: str, command: tuple[str, ...], group_name: str) -> None: ...

    def interrupt(self, target: str) -> None: ...

    def kill_session(self, session: str, *, checked: bool = True) -> None: ...

    def kill_window(self, window: str, window_name: str, *, checked: bool = True) -> None: ...

    def status(self, session: str, window: str | None = None) -> CommandResult: ...

    def select_window(self, window: str, window_name: str) -> None: ...

    def select_pane(self, target: str, group_name: str) -> None: ...

    def attach(self, session: str) -> None: ...

    def capture(self, target: str, message: str) -> CommandResult: ...

    def startup_state(self, target: str, title: str) -> CommandResult: ...


class ScenarioBackend(Protocol):
    def start(self, plan: ScenarioPlan) -> ScenarioResult: ...
    def stop(self, plan: ScenarioTarget) -> ScenarioResult: ...
    def down(self, plan: ScenarioTarget) -> ScenarioResult: ...
    def status(self, plan: ScenarioTarget) -> ScenarioResult: ...
    def attach(
        self, plan: ScenarioTarget, instance_name: str | None = None, group_name: str | None = None
    ) -> ScenarioResult: ...
    def logs(
        self,
        plan: ScenarioTarget,
        instance_name: str | None = None,
        group_name: str | None = None,
        *,
        follow: bool = False,
    ) -> ScenarioResult: ...
