"""Bind a working directory to one toolchain project manifest."""

from __future__ import annotations

import os
import re
import shlex
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

from .config.loader import load_config
from .errors import SourceLocation, WorkspaceError

WORKSPACE_DIR = ".toolchain"
WORKSPACE_FILE = "context.yaml"
DEFAULT_CONFIG_FILE = "toolchain.yaml"
WORKSPACE_VERSION = 1
ALIAS_NAME = re.compile(r"^[A-Za-z][A-Za-z0-9_-]{0,62}$")
ALIAS_HEADER = "# Generated by toolchain. Do not edit."


@dataclass(frozen=True)
class WorkspaceInitialization:
    root: Path
    config_path: Path
    stored_path: Path
    changed: bool
    alias_path: Path | None = None
    alias_changed: bool = False


def workspace_file(root: str | Path) -> Path:
    return Path(root).resolve() / WORKSPACE_DIR / WORKSPACE_FILE


def resolve_config_path(
    explicit_path: str | Path | None,
    *,
    root: str | Path | None = None,
) -> Path:
    """Resolve the manifest without searching any parent directories."""

    workspace_root = Path.cwd().resolve() if root is None else Path(root).resolve()
    if explicit_path is not None:
        return _resolve_from_root(workspace_root, Path(explicit_path).expanduser())

    marker = workspace_file(workspace_root)
    if marker.is_file():
        return _read_workspace_config(marker, workspace_root)
    return (workspace_root / DEFAULT_CONFIG_FILE).resolve()


def initialize_workspace(
    config_path: str | Path,
    *,
    root: str | Path | None = None,
    force: bool = False,
    alias: str | None = None,
) -> WorkspaceInitialization:
    """Validate a manifest and persist its binding in the selected directory."""

    workspace_root = Path.cwd().resolve() if root is None else Path(root).resolve()
    manifest_path = _resolve_from_root(workspace_root, Path(config_path).expanduser())
    load_config(manifest_path)

    marker = workspace_file(workspace_root)
    stored_path = _portable_path(manifest_path, workspace_root)
    alias_plan = (
        _plan_alias(workspace_root, stored_path, alias, force=force) if alias is not None else None
    )
    binding_changed = True
    if marker.exists():
        current_path = _read_workspace_config(marker, workspace_root)
        if current_path == manifest_path:
            binding_changed = False
        elif not force:
            raise WorkspaceError(
                f"workspace is already initialized with {current_path}; use --force to replace it",
                SourceLocation(marker),
            )

    if binding_changed:
        marker.parent.mkdir(parents=True, exist_ok=True)
        payload = yaml.safe_dump(
            {"version": WORKSPACE_VERSION, "config": str(stored_path)},
            sort_keys=False,
            allow_unicode=True,
        )
        _atomic_write(marker, payload)

    alias_path = alias_plan[0] if alias_plan is not None else None
    alias_changed = alias_plan[2] if alias_plan is not None else False
    if alias_plan is not None:
        path, content, changed = alias_plan
        if changed:
            _atomic_write(path, content, mode=0o755)
        else:
            os.chmod(path, path.stat().st_mode | 0o111)
    return WorkspaceInitialization(
        workspace_root,
        manifest_path,
        stored_path,
        binding_changed,
        alias_path,
        alias_changed,
    )


def _plan_alias(
    workspace_root: Path,
    stored_path: Path,
    name: str,
    *,
    force: bool,
) -> tuple[Path, str, bool]:
    if not ALIAS_NAME.fullmatch(name) or name == "toolchain":
        raise WorkspaceError(
            f"invalid command alias {name!r}; use a non-reserved name containing "
            "letters, digits, '_' or '-'",
            SourceLocation(workspace_root),
        )
    path = workspace_root / name
    content = _alias_script(stored_path)
    if path.is_symlink():
        if not force:
            raise WorkspaceError(
                f"command alias target already exists: {path}; use --force to replace it",
                SourceLocation(path),
            )
        return path, content, True
    if path.exists():
        try:
            existing = path.read_text(encoding="utf-8")
        except OSError as exc:
            raise WorkspaceError(str(exc), SourceLocation(path)) from exc
        if existing == content:
            return path, content, False
        if not force:
            raise WorkspaceError(
                f"command alias target already exists: {path}; use --force to replace it",
                SourceLocation(path),
            )
    return path, content, True


def _alias_script(stored_path: Path) -> str:
    if stored_path.is_absolute():
        config = f"config_path={shlex.quote(str(stored_path))}"
    else:
        config = f'config_path="$workspace_root"/{shlex.quote(str(stored_path))}'
    return "\n".join(
        (
            "#!/bin/sh",
            ALIAS_HEADER,
            "set -eu",
            'workspace_root=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)',
            config,
            'exec toolchain --config "$config_path" "$@"',
            "",
        )
    )


def _resolve_from_root(root: Path, path: Path) -> Path:
    if not path.is_absolute():
        path = root / path
    return path.resolve()


def _portable_path(config_path: Path, root: Path) -> Path:
    try:
        return config_path.relative_to(root)
    except ValueError:
        return config_path


def _read_workspace_config(marker: Path, root: Path) -> Path:
    try:
        data: Any = yaml.safe_load(marker.read_text(encoding="utf-8"))
    except OSError as exc:
        raise WorkspaceError(str(exc), SourceLocation(marker)) from exc
    except yaml.YAMLError as exc:
        raise WorkspaceError(f"invalid workspace YAML: {exc}", SourceLocation(marker)) from exc

    if not isinstance(data, dict):
        raise WorkspaceError("workspace context must be a mapping", SourceLocation(marker))
    if data.get("version") != WORKSPACE_VERSION:
        raise WorkspaceError(
            f"unsupported workspace context version: {data.get('version')!r}",
            SourceLocation(marker),
        )
    configured = data.get("config")
    if not isinstance(configured, str) or not configured.strip():
        raise WorkspaceError("workspace config must be a non-empty path", SourceLocation(marker))
    return _resolve_from_root(root, Path(configured).expanduser())


def _atomic_write(path: Path, content: str, *, mode: int | None = None) -> None:
    temporary_name: str | None = None
    try:
        with tempfile.NamedTemporaryFile(
            "w",
            encoding="utf-8",
            dir=path.parent,
            prefix=f".{path.name}.",
            delete=False,
        ) as stream:
            stream.write(content)
            temporary_name = stream.name
        if mode is not None:
            os.chmod(temporary_name, mode)
        os.replace(temporary_name, path)
    except OSError as exc:
        raise WorkspaceError(str(exc), SourceLocation(path)) from exc
    finally:
        if temporary_name is not None:
            Path(temporary_name).unlink(missing_ok=True)
