"""Deploy scenarios with Docker Compose and generated supervisord programs.

One scenario instance maps to one Compose service, so each instance owns one
``<service>.conf`` whose programs are that instance's groups.
"""

from __future__ import annotations

import shlex

from ...errors import BackendUnavailableError, ScenarioExecutionError, ScenarioPlanError
from ...execution import CommandResult, CommandRunner, SubprocessRunner
from ...scenarios.models import (
    ComposeSupervisorPlan,
    ScenarioGroupPlan,
    ScenarioInstancePlan,
    ScenarioResult,
)
from ...scenarios.process import process_argv

GENERATED_HEADER = "; Generated by toolchain. Do not edit.\n"


class ComposeSupervisorBackend:
    def __init__(self, runner: CommandRunner | None = None) -> None:
        self.runner = runner or SubprocessRunner()

    def start(self, plan: ComposeSupervisorPlan) -> ScenarioResult:
        self._check_available()
        self._write_configs(plan)
        self._checked((*self._base(plan), "up", "-d"), "Docker Compose up failed")
        return ScenarioResult(plan.scene_name, plan.profile_name, f"compose:{plan.project_name}")

    def stop(self, plan: ComposeSupervisorPlan) -> ScenarioResult:
        self._check_available()
        self._checked((*self._base(plan), "down"), "Docker Compose down failed", capture=False)
        return ScenarioResult(plan.scene_name, plan.profile_name, "stopped")

    def status(self, plan: ComposeSupervisorPlan) -> ScenarioResult:
        self._check_available()
        result = self._checked((*self._base(plan), "ps"), "Docker Compose ps failed")
        return ScenarioResult(plan.scene_name, plan.profile_name, result.stdout.rstrip())

    def attach(
        self,
        plan: ComposeSupervisorPlan,
        instance_name: str | None = None,
        group_name: str | None = None,
    ) -> ScenarioResult:
        raise ScenarioPlanError(
            "attach is only available for tmux profiles; use scene logs for deployment"
        )

    def logs(
        self,
        plan: ComposeSupervisorPlan,
        instance_name: str | None = None,
        group_name: str | None = None,
        *,
        follow: bool = False,
    ) -> ScenarioResult:
        self._check_available()
        command = [*self._base(plan), "logs"]
        if follow:
            command.append("--follow")
        service = self._service(plan, instance_name, group_name)
        if service is not None:
            command.append(service)
        result = self._checked(tuple(command), "Docker Compose logs failed", capture=not follow)
        return ScenarioResult(plan.scene_name, plan.profile_name, result.stdout.rstrip())

    def _write_configs(self, plan: ComposeSupervisorPlan) -> None:
        try:
            plan.supervisor_config_dir.mkdir(parents=True, exist_ok=True)
            services = list(
                dict.fromkeys(instance.service or "" for instance in plan.instances)
            )
            expected = {f"{service}.conf" for service in services}
            for path in plan.supervisor_config_dir.glob("*.conf"):
                if path.name not in expected and path.read_text(encoding="utf-8").startswith(
                    GENERATED_HEADER
                ):
                    path.unlink()
            for service in services:
                groups = tuple(
                    group
                    for instance in plan.instances
                    if instance.service == service
                    for group in instance.groups
                )
                path = plan.supervisor_config_dir / f"{service}.conf"
                content = render_supervisor_config(groups)
                if not path.exists() or path.read_text(encoding="utf-8") != content:
                    path.write_text(content, encoding="utf-8")
        except OSError as exc:
            raise ScenarioExecutionError(f"cannot write supervisord configuration: {exc}") from exc

    def _base(self, plan: ComposeSupervisorPlan) -> tuple[str, ...]:
        return (
            "docker",
            "compose",
            "-f",
            str(plan.compose_file),
            "--project-name",
            plan.project_name,
        )

    def _check_available(self) -> None:
        try:
            result = self.runner.run(("docker", "compose", "version"), capture=True)
        except OSError as exc:
            raise BackendUnavailableError(f"cannot execute Docker Compose: {exc}") from exc
        if result.returncode:
            raise BackendUnavailableError("Docker Compose is unavailable")

    def _checked(
        self,
        command: tuple[str, ...],
        message: str,
        *,
        capture: bool = True,
    ) -> CommandResult:
        try:
            result = self.runner.run(command, capture=capture)
        except OSError as exc:
            raise BackendUnavailableError(f"{message}: {exc}") from exc
        if result.returncode:
            detail = (result.stderr or result.stdout).strip()
            suffix = f": {detail}" if detail else f" (exit {result.returncode})"
            raise ScenarioExecutionError(message + suffix)
        return result

    def _service(
        self,
        plan: ComposeSupervisorPlan,
        instance_name: str | None,
        group_name: str | None,
    ) -> str | None:
        if group_name is not None:
            candidates = [
                instance
                for instance in plan.instances
                if (instance_name is None or instance.name == instance_name)
                and any(group.name == group_name for group in instance.groups)
            ]
            if not candidates:
                raise ScenarioPlanError(f"unknown scenario group {group_name!r}")
            if len(candidates) > 1:
                names = ", ".join(instance.name for instance in candidates)
                raise ScenarioPlanError(
                    f"group {group_name!r} runs in several instances ({names}); "
                    "select one with --instance"
                )
            return candidates[0].service
        if instance_name is not None:
            return self._instance(plan, instance_name).service
        return None

    def _instance(self, plan: ComposeSupervisorPlan, name: str) -> ScenarioInstancePlan:
        for instance in plan.instances:
            if instance.name == name:
                return instance
        raise ScenarioPlanError(f"unknown scenario instance {name!r}")


def render_supervisor_config(groups: tuple[ScenarioGroupPlan, ...]) -> str:
    blocks = [GENERATED_HEADER]
    for group in groups:
        options = group.supervisor
        command = _escape_percent(shlex.join(process_argv(group)))
        lines = [
            f"[program:{group.name}]",
            f"command={command}",
            "autostart=true",
            f"autorestart={options.autorestart}",
            f"priority={options.priority}",
            f"startsecs={options.startsecs}",
            f"startretries={options.startretries}",
            f"stopsignal={options.stopsignal}",
            f"stopasgroup={'true' if options.stopasgroup else 'false'}",
            f"killasgroup={'true' if options.killasgroup else 'false'}",
            f"stopwaitsecs={options.stopwaitsecs}",
            "redirect_stderr=true",
            "stdout_logfile=/dev/fd/1",
            "stdout_logfile_maxbytes=0",
        ]
        if group.user is not None:
            lines.append(f"user={_escape_percent(group.user)}")
        if group.workdir is not None:
            lines.append(f"directory={_escape_percent(group.workdir)}")
        if group.environment:
            rendered = ",".join(
                f'{key}="{_quote_environment(value)}"' for key, value in group.environment
            )
            lines.append(f"environment={rendered}")
        blocks.append("\n".join(lines) + "\n")
    return "\n".join(blocks)


def _escape_percent(value: str) -> str:
    return value.replace("%", "%%")


def _quote_environment(value: str) -> str:
    return _escape_percent(value).replace("\\", "\\\\").replace('"', '\\"')
