description: Example builds

native:
  description: Example container build
  container: robot-development
  start_container: true
  script: ${CONTAINER_WORKSPACE_ROOT}/scripts/build-native.sh
  interpreter: [/bin/bash, -euo, pipefail]
  workdir: ${CONTAINER_WORKSPACE_ROOT}
  setup: [/opt/ros/humble/setup.bash]
  environment:
    BUILD_TYPE:
      default: Release
      prompt:
        mode: select
        message: Select the build type
        options: [Debug, Release, RelWithDebInfo]
    PARALLEL_JOBS:
      default: "4"
      prompt:
        mode: input
        message: Enter the parallel job count
