"""Bind a working directory to one Rigyard project manifest."""

from __future__ import annotations

import os
import shlex
import sys
import sysconfig
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

from .config.loader import load_config
from .config.models import COMMAND_ALIAS_NAME
from .errors import SourceLocation, WorkspaceError

WORKSPACE_DIR = ".rigyard"
WORKSPACE_FILE = "context.yaml"
DEFAULT_CONFIG_FILE = "rigyard.yaml"
WORKSPACE_VERSION = 1
ALIAS_HEADER = "# Generated by rigyard. Do not edit."
ALIAS_VERSION_HEADER = "# Rigyard alias version: 1"
ALIAS_CONFIG_PREFIX = "# Rigyard configuration: "


@dataclass(frozen=True)
class WorkspaceInitialization:
    root: Path
    config_path: Path
    stored_path: Path
    changed: bool
    alias_path: Path | None = None
    alias_changed: bool = False


@dataclass(frozen=True)
class AliasRemoval:
    path: Path
    removed: bool


def workspace_file(root: str | Path) -> Path:
    return Path(root).resolve() / WORKSPACE_DIR / WORKSPACE_FILE


def resolve_config_path(
    explicit_path: str | Path | None,
    *,
    root: str | Path | None = None,
) -> Path:
    """Resolve the manifest without searching any parent directories."""

    workspace_root = Path.cwd().resolve() if root is None else Path(root).resolve()
    if explicit_path is not None:
        return _resolve_from_root(workspace_root, Path(explicit_path).expanduser())

    marker = workspace_file(workspace_root)
    if marker.is_file():
        return _read_workspace_config(marker, workspace_root)
    return (workspace_root / DEFAULT_CONFIG_FILE).resolve()


def initialize_workspace(
    config_path: str | Path,
    *,
    root: str | Path | None = None,
    force: bool = False,
    alias: str | None = None,
    use_config_alias: bool = True,
) -> WorkspaceInitialization:
    """Validate a manifest and persist its binding in the selected directory."""

    workspace_root = Path.cwd().resolve() if root is None else Path(root).resolve()
    manifest_path = _resolve_from_root(workspace_root, Path(config_path).expanduser())
    config = load_config(manifest_path)
    selected_alias = alias
    if selected_alias is None and use_config_alias:
        selected_alias = config.workspace.command_alias

    marker = workspace_file(workspace_root)
    stored_path = _portable_path(manifest_path, workspace_root)
    alias_plan = (
        _plan_alias(manifest_path, selected_alias, force=force)
        if selected_alias is not None
        else None
    )
    binding_changed = True
    if marker.exists():
        current_path = _read_workspace_config(marker, workspace_root)
        if current_path == manifest_path:
            binding_changed = False
        elif not force:
            raise WorkspaceError(
                f"workspace is already initialized with {current_path}; use --force to replace it",
                SourceLocation(marker),
            )

    if binding_changed:
        marker.parent.mkdir(parents=True, exist_ok=True)
        payload = yaml.safe_dump(
            {"version": WORKSPACE_VERSION, "config": str(stored_path)},
            sort_keys=False,
            allow_unicode=True,
        )
        _atomic_write(marker, payload)

    alias_path = alias_plan[0] if alias_plan is not None else None
    alias_changed = alias_plan[2] if alias_plan is not None else False
    if alias_plan is not None:
        path, content, changed = alias_plan
        if changed:
            _atomic_write(path, content, mode=0o755)
        else:
            os.chmod(path, path.stat().st_mode | 0o111)
    return WorkspaceInitialization(
        workspace_root,
        manifest_path,
        stored_path,
        binding_changed,
        alias_path,
        alias_changed,
    )


def remove_environment_alias(
    config_path: str | Path,
    name: str | None = None,
) -> AliasRemoval:
    """Remove this project's generated command alias from the active Python environment."""

    manifest_path = Path(config_path).expanduser().resolve()
    config = load_config(manifest_path)
    selected = name or config.workspace.command_alias
    if selected is None:
        raise WorkspaceError(
            "no command alias was supplied or configured; pass an alias name to remove"
        )
    _validate_alias_name(selected, manifest_path)
    path = _active_environment_scripts_dir() / selected
    if not path.exists() and not path.is_symlink():
        return AliasRemoval(path, False)
    if path.is_symlink():
        raise WorkspaceError(
            f"refusing to remove symbolic link at command alias path: {path}",
            SourceLocation(path),
        )
    try:
        content = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise WorkspaceError(str(exc), SourceLocation(path)) from exc
    if not _is_project_alias(content, manifest_path):
        raise WorkspaceError(
            f"refusing to remove command alias not generated for this configuration: {path}",
            SourceLocation(path),
        )
    try:
        path.unlink()
    except OSError as exc:
        raise WorkspaceError(str(exc), SourceLocation(path)) from exc
    return AliasRemoval(path, True)


def _plan_alias(
    manifest_path: Path,
    name: str,
    *,
    force: bool,
) -> tuple[Path, str, bool]:
    _validate_alias_name(name, manifest_path)
    path = _active_environment_scripts_dir() / name
    content = _alias_script(manifest_path)
    if path.is_symlink():
        if not force:
            raise WorkspaceError(
                f"command alias target already exists: {path}; use --force to replace it",
                SourceLocation(path),
            )
        return path, content, True
    if path.exists():
        try:
            existing = path.read_text(encoding="utf-8")
        except OSError as exc:
            raise WorkspaceError(str(exc), SourceLocation(path)) from exc
        if existing == content:
            return path, content, False
        if not force:
            raise WorkspaceError(
                f"command alias target already exists: {path}; use --force to replace it",
                SourceLocation(path),
            )
    return path, content, True


def _alias_script(manifest_path: Path) -> str:
    config_path = manifest_path.resolve()
    return "\n".join(
        (
            "#!/bin/sh",
            ALIAS_HEADER,
            ALIAS_VERSION_HEADER,
            f"{ALIAS_CONFIG_PREFIX}{config_path}",
            "set -eu",
            f"exec {shlex.quote(sys.executable)} -m rigyard --config "
            f"{shlex.quote(str(config_path))} \"$@\"",
            "",
        )
    )


def _validate_alias_name(name: str, location: Path) -> None:
    if not COMMAND_ALIAS_NAME.fullmatch(name) or name == "rigyard":
        raise WorkspaceError(
            f"invalid command alias {name!r}; use a non-reserved name containing "
            "letters, digits, '_' or '-'",
            SourceLocation(location),
        )


def _is_project_alias(content: str, manifest_path: Path) -> bool:
    lines = content.splitlines()
    return len(lines) >= 4 and lines[:4] == [
        "#!/bin/sh",
        ALIAS_HEADER,
        ALIAS_VERSION_HEADER,
        f"{ALIAS_CONFIG_PREFIX}{manifest_path.resolve()}",
    ]


def _active_environment_scripts_dir() -> Path:
    """Return the scripts directory for the active, matching Conda or venv environment."""

    active = os.environ.get("VIRTUAL_ENV") or os.environ.get("CONDA_PREFIX")
    if not active:
        raise WorkspaceError(
            "command aliases require an active Conda or virtual environment; "
            "activate the environment that provides rigyard or use --no-alias"
        )
    active_prefix = Path(active).expanduser().resolve()
    runtime_prefix = Path(sys.prefix).resolve()
    if runtime_prefix != active_prefix:
        raise WorkspaceError(
            f"active Python environment {active_prefix} does not provide the running rigyard "
            f"interpreter ({runtime_prefix}); install rigyard in the active environment"
        )
    scripts = Path(sysconfig.get_path("scripts")).resolve()
    try:
        scripts.relative_to(active_prefix)
    except ValueError as exc:
        raise WorkspaceError(
            f"Python scripts directory {scripts} is outside the active environment {active_prefix}"
        ) from exc
    if not scripts.is_dir():
        raise WorkspaceError(
            f"Python scripts directory does not exist: {scripts}",
            SourceLocation(scripts),
        )
    return scripts


def _resolve_from_root(root: Path, path: Path) -> Path:
    if not path.is_absolute():
        path = root / path
    return path.resolve()


def _portable_path(config_path: Path, root: Path) -> Path:
    try:
        return config_path.relative_to(root)
    except ValueError:
        return config_path


def _read_workspace_config(marker: Path, root: Path) -> Path:
    try:
        data: Any = yaml.safe_load(marker.read_text(encoding="utf-8"))
    except OSError as exc:
        raise WorkspaceError(str(exc), SourceLocation(marker)) from exc
    except yaml.YAMLError as exc:
        raise WorkspaceError(f"invalid workspace YAML: {exc}", SourceLocation(marker)) from exc

    if not isinstance(data, dict):
        raise WorkspaceError("workspace context must be a mapping", SourceLocation(marker))
    if data.get("version") != WORKSPACE_VERSION:
        raise WorkspaceError(
            f"unsupported workspace context version: {data.get('version')!r}",
            SourceLocation(marker),
        )
    configured = data.get("config")
    if not isinstance(configured, str) or not configured.strip():
        raise WorkspaceError("workspace config must be a non-empty path", SourceLocation(marker))
    return _resolve_from_root(root, Path(configured).expanduser())


def _atomic_write(path: Path, content: str, *, mode: int | None = None) -> None:
    temporary_name: str | None = None
    try:
        with tempfile.NamedTemporaryFile(
            "w",
            encoding="utf-8",
            dir=path.parent,
            prefix=f".{path.name}.",
            delete=False,
        ) as stream:
            stream.write(content)
            temporary_name = stream.name
        if mode is not None:
            os.chmod(temporary_name, mode)
        os.replace(temporary_name, path)
    except OSError as exc:
        raise WorkspaceError(str(exc), SourceLocation(path)) from exc
    finally:
        if temporary_name is not None:
            Path(temporary_name).unlink(missing_ok=True)
